name: Tests

on:
  pull_request:
    branches:
    - master

  push:
    branches:
    - master

jobs:

  set_matrix:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - id: set-matrix
      shell: bash
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "::set-output name=matrix::{\"os\":[\"ubuntu-latest\"], \"python-version\":[3.8]}"
        else
          echo "::set-output name=matrix::{\"os\":[\"ubuntu-latest\", \"windows-latest\"], \"python-version\":[3.8]}"
        fi

  test_install:

    runs-on: ${{ matrix.os }}
    needs: set_matrix

    strategy:
      matrix: ${{fromJSON(needs.set_matrix.outputs.matrix)}}
      fail-fast: false

    steps:
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install via pip from github
      run: |
        pip install --user -U pip
        pip install wheel
        pip install git+https://github.com/gazprom-neft/seismiqb.git@${{ github.sha }}#egg=seismiqb[test]

    - name: Run 'import' in installed environment
      run: python -c 'import seismiqb'

    - name: Checkout SeismiQB
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run basic tests
      env:
        BASE_DIR: ${{ github.workspace }}
      run: |
        pip install -U pytest
        pytest -m "not slow" --tb=line --disable-pytest-warnings -v --pyargs
